name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 增加超时时间
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zip \
          unzip \
          libltdl-dev \
          libffi-dev \
          libssl-dev \
          lld
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install buildozer
        pip install cython==0.29.33
        pip install virtualenv
        pip install kivy==2.1.0
        pip install pillow
    
    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.gradle
          ~/.android
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Generate buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          echo "Created buildozer.spec"
        else
          echo "buildozer.spec already exists"
        fi
    
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin/
        # 使用--verbose获取详细日志
        buildozer android debug --verbose
      env:
        ANDROID_HOME: /usr/lib/android-sdk
        ANDROID_SDK_ROOT: /usr/lib/android-sdk
    
    - name: Find and upload APK
      run: |
        # 查找所有APK文件
        find bin -name '*.apk' -exec echo "Found APK: {}" \;
        
        # 重命名APK文件为固定名称
        for apk in bin/*.apk; do
          new_name="SearchLikeBot-${{ github.run_number }}.apk"
          cp "$apk" "$new_name"
          echo "Renamed $apk to $new_name"
        done
      id: find_apk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SearchLikeBot-APK
        path: SearchLikeBot-*.apk
    
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          自动构建版本 v${{ github.run_number }}
          
          ## 构建信息
          - 提交SHA: ${{ github.sha }}
          - 触发分支: ${{ github.ref }}
          
          ## 安装说明
          下载附件APK文件并安装
        draft: false
        prerelease: false
        files: SearchLikeBot-*.apk