name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zip \
          unzip \
          libltdl-dev \
          libffi-dev \
          libssl-dev \
          lld
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install buildozer
        pip install cython==0.29.33
        pip install virtualenv
        pip install kivy==2.1.0
        pip install pillow
    
    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.gradle
          ~/.android
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin/
        yes | buildozer android debug
      env:
        ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
        ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: SearchLikeBot-APK
        path: bin/*.apk
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          自动构建版本 v${{ github.run_number }}
          
          ## 更新内容
          - 自动构建的APK文件
          - 提交SHA: ${{ github.sha }}
          
          ## 下载
          请下载下方的APK文件进行安装
        draft: false
        prerelease: false
    
    - name: Upload Release APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/searchlikebot-0.1-arm64-v8a-debug.apk
        asset_name: SearchLikeBot-v${{ github.run_number }}.apk
        asset_content_type: application/vnd.android.package-archive
